### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by dxphilo** [chenbowu/mini-vue#1]
Sorry to open this unrelated issue. I came across this repo and the TS challenges seems interesting. Where can I get the challenges and test them out ? again sorry this unrelated issue.

**Comment by chenbowu** [comment]
[[type-challenges/type-challenges](https://github.com/type-challenges/type-challenges)](https://github.com/type-challenges/type-challenges)

**Comment by dxphilo** [comment]
> [[type-challenges/type-challenges](https://github.com/type-challenges/type-challenges)](https://github.com/type-challenges/type-challenges)

Thank you 🙏 . I'll close this at the moment.
